name: dart_buoy
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0-108.0.dev <3.0.0'

dependencies:
  http: ^0.13.4
  amaxdart:
    path: ../amaxdart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
