name: amaxdart
description: Armonia Meta Chain RPC API client in Dart language
version: 0.4.8+20220418
homepage: https://github.com/niclas9/amaxdart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.3.0
  pointycastle: ^3.3.5
  amaxdart_ecc: ^0.4.4
  common_utils: ^2.1.0
  test: ^1.5.1


